### PR TITLE
Update security model

### PR DESCRIPTION
**Pull request by Ferrariic**
https://github.com/Bot-detector/Bot-Detector-Core-Files/issues/147

### CODE REVIEW

**Comment by ThorntonMatthewD** [comment]
Does tables.txt need included?

**Comment by Ferrariic** [comment]
> Does tables.txt need included?

Good call, removed.

**Review by ThorntonMatthewD — APPROVED** [review]
This is so much easier to understand than what we had before!!!

**Comment by Ferrariic** [comment]
> This is so much easier to understand than what we had before!!!

big thanks to @extreme4all we worked on it together today :D

**Pull request merged**
