### PR TITLE
write test cases

### PR DESCRIPTION
**Pull request by Ferrariic**

### CODE REVIEW

**Review by extreme4all — CHANGES_REQUESTED** [review]
test cases failed

```
FAILED tests/test_feedback.py::test_post_feedback - AssertionError: Test: 1 | Invalid response 201
FAILED tests/test_hiscore.py::test_get_account_hiscore_xp_change - sqlalchemy.exc.OperationalError: (asyncmy.errors.OperationalError) (1054, "Unknown column 'playerHiscoreDataXPChange.phosanis_nightmare' ...FAILED tests/test_hiscore.py::test_post_hiscore - AssertionError: Test: 0 | Invalid response 422
FAILED tests/test_legacy.py::test_get_prediction - AssertionError: invalid response 200
```
either resolve or exclude & fix in 4 seperate issues.
note: test cases were run on prod environment

**Comment by Ferrariic** [comment]
Stable in prod, except for a lockout timer which seems to be due to the server itself.

**Comment by Ferrariic** [comment]
@extreme4all @ThorntonMatthewD when possible could this be re-reviewed ty!

**Review by extreme4all — APPROVED** [review]
tests run, commented out inserts to not pollute environments until we can properly support these cases

**Pull request merged**
