### PR TITLE
seperate yaml files

### PR DESCRIPTION
**Pull request by extreme4all**

### CODE REVIEW

**Review by ThorntonMatthewD — CHANGES_REQUESTED** [review]
The horizontal pod scalers will require both a CPU resource request on both dev and prod. It will be how they determine what 50% CPU utilization is for the pods.

https://github.com/Bot-detector/Bot-Detector-Core-Files/blob/0f1964b7c3cf58e2feb7c351fe305b7eef1277dc/deployment/dev-deployment.yaml#L33

It'll go in the section above.

```
containers:
   resources:
      requests:
         cpu: "1000m" (or whatever)
```

The file path for the pod deployment file, and the additional files, will need to be placed here in the workflow (and also in the prod one):
https://github.com/Bot-detector/Bot-Detector-Core-Files/blob/0f1964b7c3cf58e2feb7c351fe305b7eef1277dc/.github/workflows/development-workflow.yml#L42

**Comment by extreme4all** [comment]
instead of requesting cpu
> ```
> containers:
>    resources:
>       requests:
>          cpu: "1000m" (or whatever)
> ```
shouldnt we set a limit?
```
resources:
  limits:
    cpu: "1"
```

**Comment by ThorntonMatthewD** [comment]
Adding a limit also would be good.

**Comment by ThorntonMatthewD** [comment]
I'm pretty sure HPAs run off of the requests and not the limits, though.

**Comment by extreme4all** [comment]
we might need to up date to Kubernetes v1.23
https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/

**Review by ThorntonMatthewD — APPROVED** [review]

**Pull request merged**
